/**
 * Default CAD generation prompts for animated text display
 */
export const DEFAULT_CAD_PROMPTS = [
  'A 320MM VENTED BRAKE ROTOR WITH 5 M12 HOLES ON 114.3MM PCD',
  'A STEEL BRACKET WITH 4 MOUNTING HOLES',
  'A CIRCULAR PLATE WITH CENTER HOLE',
  'A STEEL BEAM WITH I-SECTION PROFILE',
  'A CUSTOM GEAR WITH 24 TEETH',
];






